# Generated by Django 3.2.5 on 2021-07-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_user', models.IntegerField()),
                ('ref', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('cashier_user', models.IntegerField()),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('item', models.CharField(max_length=250)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
