# Generated by Django 3.2.5 on 2021-07-14 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt_ref',
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='ref',
        ),
        migrations.AlterField(
            model_name='receipts',
            name='cashier_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashier_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
