# Generated by Django 3.2.5 on 2021-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_app', '0002_auto_20210714_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='cashier_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
