# Generated by Django 3.2.5 on 2021-07-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_app', '0004_globalvariables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalVariables',
        ),
    ]
